plugins {
    id 'java'
    id 'maven-publish'
    id 'io.spring.dependency-management' version '1.1.7'
    id "com.google.cloud.artifactregistry.gradle-plugin" version "2.2.0"
}

group = "com.gcp.agent25"
version = "1.0.1"

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/snapshot' }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

ext {
    SPRINGBOOT_VERSION = '3.4.4'
    JUNIT_VERSION = '5.10.0'
    JUNIT_PLATFORM_VERSION = '1.11.4'
    LOMBOK_VERSION = '1.18.22'
    LOGGER_VERSION = '2.1.0-alpha1'
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-webflux:${SPRINGBOOT_VERSION}"
    implementation "org.springframework.boot:spring-boot-starter-validation:${SPRINGBOOT_VERSION}"
    implementation "org.springframework.boot:spring-boot-starter-web:${SPRINGBOOT_VERSION}"
    implementation "org.slf4j:slf4j-api:${LOGGER_VERSION}"

    compileOnly "org.projectlombok:lombok:${LOMBOK_VERSION}"
    annotationProcessor "org.projectlombok:lombok:${LOMBOK_VERSION}"

    testCompileOnly "org.projectlombok:lombok:${LOMBOK_VERSION}"
    testAnnotationProcessor "org.projectlombok:lombok:${LOMBOK_VERSION}"

    testImplementation "org.junit.jupiter:junit-jupiter:${JUNIT_VERSION}"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${SPRINGBOOT_VERSION}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${JUNIT_PLATFORM_VERSION}"

}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        mavenLocal()
        maven {
            def releaseURL = "artifactregistry://asia-southeast1-maven.pkg.dev/gcp-25-adk-ai-agent/ai-agent-common-core"
            url releaseURL
            credentials {
                username = "oauth2accesstoken"
                password = System.getenv("GCP25_ACCESS_TOKEN")
            }
        }
    }
}

repositories {
    maven {
        url "artifactregistry://asia-southeast1-maven.pkg.dev/gcp-25-adk-ai-agent/ai-agent-common-core"
    }
}

tasks.test {
    useJUnitPlatform()
}